### ISSUE TITLE
Can't add tag when click "done" keyboard Adroid in version 0.0.17

### ISSUE THREAD

**Issue by mrh2v** [jwohlfert23/react-native-tag-input#48]
In version 0.0.17, I can't add new tag when click button "done" in keyboard ? This does not happen in version 0.0.16

**Comment by Ashoat** [comment]
Please be more specific in your bug reports. Two-sentence issues almost always end up wasting contributors' time, because we end up having to ask you more questions that you could've just answered initially.

First of all, please provide the code you're using.

Second of all, are you referring to the `parseOnBlur` parameter? I just checked out 0.0.16 to test, and clicking the "Done" button on the example doesn't do anything. Actually, it doesn't do anything if `parseOnBlur` is set to true either...
