### ISSUE TITLE
Tags and Tag Input are not center aligned

### ISSUE THREAD

**Issue by alexgurr** [jwohlfert23/react-native-tag-input#54]
https://puu.sh/zjudZ/75c53262a0.png

Can't seem to override this with any styles either?

**Comment by Ashoat** [comment]
This issue doesn't appear in the example project (in this repo), so I'm guessing it has to do with the styles you're using. Are you rendering the `TagInput` with any props that specify custom styles? If so, what are those styles? What is the style of the component containing your `TagInput`?

In the future, providing a GitHub repo containing a project that demonstrates the bug is the surest way of getting help, and reduces the amount of back-and-forth between issue reporters and package authors.
