### ISSUE TITLE
Placeholder not updating

### ISSUE THREAD

**Issue by gauravsbagul** [jwohlfert23/react-native-tag-input#80]
I am trying to update the placeholder but it is not working. any solution please
`"dependencies": {
"@react-native-community/async-storage": "^1.6.1",
"@react-native-community/netinfo": "^4.2.1",
"axios": "^0.19.0",
"jetifier": "^1.6.4",
"jsonwebtoken": "^8.5.1",
"jwt-decode": "^2.2.0",
"native-base": "^2.13.8",
"pubnub-react": "^1.3.2",
"query-string": "^6.8.3",
"react": "16.8.6",
"react-native": "0.60.4",
"react-native-calendars": "^1.212.0",
"react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git",
"react-native-chart-kit": "^3.3.1",
"react-native-check-box": "^2.1.7",
"react-native-datepicker": "^1.7.2",
"react-native-document-picker": "^3.2.4",
"react-native-gesture-handler": "^1.4.1",
"react-native-gifted-chat": "^0.11.3",
"react-native-image-picker": "^1.1.0",
"react-native-linear-gradient": "^2.5.6",
"react-native-progress": "^3.6.0",
"react-native-push-notification": "^3.1.9",
"react-native-qrcode-svg": "^5.2.0",
"react-native-select-multiple": "^2.1.0",
"react-native-svg": "^9.9.3",
"react-native-table-component": "^1.2.1",
"react-native-tag-input": "0.0.21",
"react-native-vector-icons": "^6.6.0",
"react-native-video": "^5.0.2",
"react-native-video-controls": "^2.2.3",
"react-native-webview": "^7.0.5",
"react-navigation": "^3.12.1",
"react-redux": "^7.1.1",
"redux": "^4.0.4",
"redux-logger": "^3.0.6",
"redux-promise": "^0.6.0",
"redux-thunk": "^2.3.0",
"socket.io-client": "^2.3.0",
"uuid": "^3.3.3"
},`

**Comment by Ashoat** [comment]
The placeholder is set through the `inputProps` param. I haven't tried updating the placeholder before, but you'd need to make sure the `inputProps` param itself changes, since `TagInput` is a `PureComponent`. If you replace the `inputProps` parameter with a different one that contains a different `placeholder` param, and the placeholder doesn't change, it could be a bug in `TextInput`.

Unfortunately I won't be able to help you further unless I can reproduce the issue you're describing. If you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub, I can try and investigate it further.

**Comment by gauravsbagul** [comment]
I found the solution to change the placeholder thanks for the reply.

![image](https://user-images.githubusercontent.com/25247251/71652646-f76b7300-2d4c-11ea-8532-5a455aed2863.png)
